--
-- PostgreSQL database dump
--

-- Dumped from database version 15.1 (Debian 15.1-1.pgdg110+1)
-- Dumped by pg_dump version 15.1 (Debian 15.1-1.pgdg110+1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: auth_group; Type: TABLE; Schema: public; Owner: food_user
--

CREATE TABLE public.auth_group (
    id integer NOT NULL,
    name character varying(150) NOT NULL
);


ALTER TABLE public.auth_group OWNER TO food_user;

--
-- Name: auth_group_id_seq; Type: SEQUENCE; Schema: public; Owner: food_user
--

ALTER TABLE public.auth_group ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_group_permissions; Type: TABLE; Schema: public; Owner: food_user
--

CREATE TABLE public.auth_group_permissions (
    id bigint NOT NULL,
    group_id integer NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.auth_group_permissions OWNER TO food_user;

--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: food_user
--

ALTER TABLE public.auth_group_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_permission; Type: TABLE; Schema: public; Owner: food_user
--

CREATE TABLE public.auth_permission (
    id integer NOT NULL,
    name character varying(255) NOT NULL,
    content_type_id integer NOT NULL,
    codename character varying(100) NOT NULL
);


ALTER TABLE public.auth_permission OWNER TO food_user;

--
-- Name: auth_permission_id_seq; Type: SEQUENCE; Schema: public; Owner: food_user
--

ALTER TABLE public.auth_permission ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_permission_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user; Type: TABLE; Schema: public; Owner: food_user
--

CREATE TABLE public.auth_user (
    id integer NOT NULL,
    password character varying(128) NOT NULL,
    last_login timestamp with time zone,
    is_superuser boolean NOT NULL,
    username character varying(150) NOT NULL,
    first_name character varying(150) NOT NULL,
    last_name character varying(150) NOT NULL,
    email character varying(254) NOT NULL,
    is_staff boolean NOT NULL,
    is_active boolean NOT NULL,
    date_joined timestamp with time zone NOT NULL
);


ALTER TABLE public.auth_user OWNER TO food_user;

--
-- Name: auth_user_groups; Type: TABLE; Schema: public; Owner: food_user
--

CREATE TABLE public.auth_user_groups (
    id bigint NOT NULL,
    user_id integer NOT NULL,
    group_id integer NOT NULL
);


ALTER TABLE public.auth_user_groups OWNER TO food_user;

--
-- Name: auth_user_groups_id_seq; Type: SEQUENCE; Schema: public; Owner: food_user
--

ALTER TABLE public.auth_user_groups ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_groups_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user_id_seq; Type: SEQUENCE; Schema: public; Owner: food_user
--

ALTER TABLE public.auth_user ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user_user_permissions; Type: TABLE; Schema: public; Owner: food_user
--

CREATE TABLE public.auth_user_user_permissions (
    id bigint NOT NULL,
    user_id integer NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.auth_user_user_permissions OWNER TO food_user;

--
-- Name: auth_user_user_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: food_user
--

ALTER TABLE public.auth_user_user_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_user_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: core_contact; Type: TABLE; Schema: public; Owner: food_user
--

CREATE TABLE public.core_contact (
    id bigint NOT NULL,
    name character varying(50) NOT NULL,
    email character varying(254) NOT NULL,
    subject character varying(255) NOT NULL,
    message text NOT NULL,
    created_at timestamp with time zone NOT NULL
);


ALTER TABLE public.core_contact OWNER TO food_user;

--
-- Name: core_contact_id_seq; Type: SEQUENCE; Schema: public; Owner: food_user
--

ALTER TABLE public.core_contact ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.core_contact_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: core_subscriber; Type: TABLE; Schema: public; Owner: food_user
--

CREATE TABLE public.core_subscriber (
    id bigint NOT NULL,
    email character varying(254) NOT NULL,
    is_active boolean NOT NULL,
    created_at timestamp with time zone NOT NULL
);


ALTER TABLE public.core_subscriber OWNER TO food_user;

--
-- Name: core_subscriber_id_seq; Type: SEQUENCE; Schema: public; Owner: food_user
--

ALTER TABLE public.core_subscriber ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.core_subscriber_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_admin_log; Type: TABLE; Schema: public; Owner: food_user
--

CREATE TABLE public.django_admin_log (
    id integer NOT NULL,
    action_time timestamp with time zone NOT NULL,
    object_id text,
    object_repr character varying(200) NOT NULL,
    action_flag smallint NOT NULL,
    change_message text NOT NULL,
    content_type_id integer,
    user_id integer NOT NULL,
    CONSTRAINT django_admin_log_action_flag_check CHECK ((action_flag >= 0))
);


ALTER TABLE public.django_admin_log OWNER TO food_user;

--
-- Name: django_admin_log_id_seq; Type: SEQUENCE; Schema: public; Owner: food_user
--

ALTER TABLE public.django_admin_log ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_admin_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_content_type; Type: TABLE; Schema: public; Owner: food_user
--

CREATE TABLE public.django_content_type (
    id integer NOT NULL,
    app_label character varying(100) NOT NULL,
    model character varying(100) NOT NULL
);


ALTER TABLE public.django_content_type OWNER TO food_user;

--
-- Name: django_content_type_id_seq; Type: SEQUENCE; Schema: public; Owner: food_user
--

ALTER TABLE public.django_content_type ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_content_type_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_migrations; Type: TABLE; Schema: public; Owner: food_user
--

CREATE TABLE public.django_migrations (
    id bigint NOT NULL,
    app character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    applied timestamp with time zone NOT NULL
);


ALTER TABLE public.django_migrations OWNER TO food_user;

--
-- Name: django_migrations_id_seq; Type: SEQUENCE; Schema: public; Owner: food_user
--

ALTER TABLE public.django_migrations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_migrations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_session; Type: TABLE; Schema: public; Owner: food_user
--

CREATE TABLE public.django_session (
    session_key character varying(40) NOT NULL,
    session_data text NOT NULL,
    expire_date timestamp with time zone NOT NULL
);


ALTER TABLE public.django_session OWNER TO food_user;

--
-- Name: stories_category; Type: TABLE; Schema: public; Owner: food_user
--

CREATE TABLE public.stories_category (
    id bigint NOT NULL,
    name character varying(20) NOT NULL,
    background_image character varying(100) NOT NULL
);


ALTER TABLE public.stories_category OWNER TO food_user;

--
-- Name: stories_category_id_seq; Type: SEQUENCE; Schema: public; Owner: food_user
--

ALTER TABLE public.stories_category ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.stories_category_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: stories_comment; Type: TABLE; Schema: public; Owner: food_user
--

CREATE TABLE public.stories_comment (
    id bigint NOT NULL,
    text text NOT NULL,
    created_at timestamp with time zone NOT NULL,
    story_id bigint NOT NULL,
    user_id integer NOT NULL
);


ALTER TABLE public.stories_comment OWNER TO food_user;

--
-- Name: stories_comment_id_seq; Type: SEQUENCE; Schema: public; Owner: food_user
--

ALTER TABLE public.stories_comment ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.stories_comment_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: stories_story; Type: TABLE; Schema: public; Owner: food_user
--

CREATE TABLE public.stories_story (
    id bigint NOT NULL,
    title character varying(250) NOT NULL,
    description text NOT NULL,
    author_id integer NOT NULL,
    category_id bigint NOT NULL,
    created_at timestamp with time zone NOT NULL
);


ALTER TABLE public.stories_story OWNER TO food_user;

--
-- Name: stories_story_id_seq; Type: SEQUENCE; Schema: public; Owner: food_user
--

ALTER TABLE public.stories_story ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.stories_story_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: stories_story_tags; Type: TABLE; Schema: public; Owner: food_user
--

CREATE TABLE public.stories_story_tags (
    id bigint NOT NULL,
    story_id bigint NOT NULL,
    tag_id bigint NOT NULL
);


ALTER TABLE public.stories_story_tags OWNER TO food_user;

--
-- Name: stories_story_tags_id_seq; Type: SEQUENCE; Schema: public; Owner: food_user
--

ALTER TABLE public.stories_story_tags ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.stories_story_tags_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: stories_storyimage; Type: TABLE; Schema: public; Owner: food_user
--

CREATE TABLE public.stories_storyimage (
    id bigint NOT NULL,
    image character varying(100) NOT NULL,
    created_at timestamp with time zone NOT NULL,
    story_id bigint NOT NULL
);


ALTER TABLE public.stories_storyimage OWNER TO food_user;

--
-- Name: stories_storyimage_id_seq; Type: SEQUENCE; Schema: public; Owner: food_user
--

ALTER TABLE public.stories_storyimage ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.stories_storyimage_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: stories_tag; Type: TABLE; Schema: public; Owner: food_user
--

CREATE TABLE public.stories_tag (
    id bigint NOT NULL,
    name character varying(20) NOT NULL
);


ALTER TABLE public.stories_tag OWNER TO food_user;

--
-- Name: stories_tag_id_seq; Type: SEQUENCE; Schema: public; Owner: food_user
--

ALTER TABLE public.stories_tag ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.stories_tag_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: auth_group; Type: TABLE DATA; Schema: public; Owner: food_user
--

COPY public.auth_group (id, name) FROM stdin;
\.


--
-- Data for Name: auth_group_permissions; Type: TABLE DATA; Schema: public; Owner: food_user
--

COPY public.auth_group_permissions (id, group_id, permission_id) FROM stdin;
\.


--
-- Data for Name: auth_permission; Type: TABLE DATA; Schema: public; Owner: food_user
--

COPY public.auth_permission (id, name, content_type_id, codename) FROM stdin;
1	Can add log entry	1	add_logentry
2	Can change log entry	1	change_logentry
3	Can delete log entry	1	delete_logentry
4	Can view log entry	1	view_logentry
5	Can add permission	2	add_permission
6	Can change permission	2	change_permission
7	Can delete permission	2	delete_permission
8	Can view permission	2	view_permission
9	Can add group	3	add_group
10	Can change group	3	change_group
11	Can delete group	3	delete_group
12	Can view group	3	view_group
13	Can add user	4	add_user
14	Can change user	4	change_user
15	Can delete user	4	delete_user
16	Can view user	4	view_user
17	Can add content type	5	add_contenttype
18	Can change content type	5	change_contenttype
19	Can delete content type	5	delete_contenttype
20	Can view content type	5	view_contenttype
21	Can add session	6	add_session
22	Can change session	6	change_session
23	Can delete session	6	delete_session
24	Can view session	6	view_session
25	Can add subscriber	7	add_subscriber
26	Can change subscriber	7	change_subscriber
27	Can delete subscriber	7	delete_subscriber
28	Can view subscriber	7	view_subscriber
29	Can add contact	8	add_contact
30	Can change contact	8	change_contact
31	Can delete contact	8	delete_contact
32	Can view contact	8	view_contact
33	Can add category	9	add_category
34	Can change category	9	change_category
35	Can delete category	9	delete_category
36	Can view category	9	view_category
37	Can add story	10	add_story
38	Can change story	10	change_story
39	Can delete story	10	delete_story
40	Can view story	10	view_story
41	Can add tag	11	add_tag
42	Can change tag	11	change_tag
43	Can delete tag	11	delete_tag
44	Can view tag	11	view_tag
45	Can add story image	12	add_storyimage
46	Can change story image	12	change_storyimage
47	Can delete story image	12	delete_storyimage
48	Can view story image	12	view_storyimage
49	Can add comment	13	add_comment
50	Can change comment	13	change_comment
51	Can delete comment	13	delete_comment
52	Can view comment	13	view_comment
\.


--
-- Data for Name: auth_user; Type: TABLE DATA; Schema: public; Owner: food_user
--

COPY public.auth_user (id, password, last_login, is_superuser, username, first_name, last_name, email, is_staff, is_active, date_joined) FROM stdin;
1	pbkdf2_sha256$390000$LEFFXHmza56TSBJGplTntL$evmqsaq7X/Ro95SGNDnZ8j7OA8Sn8D/Z80DJtS09bgc=	\N	t	elnur				t	t	2023-04-11 15:38:44.551497+00
\.


--
-- Data for Name: auth_user_groups; Type: TABLE DATA; Schema: public; Owner: food_user
--

COPY public.auth_user_groups (id, user_id, group_id) FROM stdin;
\.


--
-- Data for Name: auth_user_user_permissions; Type: TABLE DATA; Schema: public; Owner: food_user
--

COPY public.auth_user_user_permissions (id, user_id, permission_id) FROM stdin;
\.


--
-- Data for Name: core_contact; Type: TABLE DATA; Schema: public; Owner: food_user
--

COPY public.core_contact (id, name, email, subject, message, created_at) FROM stdin;
\.


--
-- Data for Name: core_subscriber; Type: TABLE DATA; Schema: public; Owner: food_user
--

COPY public.core_subscriber (id, email, is_active, created_at) FROM stdin;
\.


--
-- Data for Name: django_admin_log; Type: TABLE DATA; Schema: public; Owner: food_user
--

COPY public.django_admin_log (id, action_time, object_id, object_repr, action_flag, change_message, content_type_id, user_id) FROM stdin;
\.


--
-- Data for Name: django_content_type; Type: TABLE DATA; Schema: public; Owner: food_user
--

COPY public.django_content_type (id, app_label, model) FROM stdin;
1	admin	logentry
2	auth	permission
3	auth	group
4	auth	user
5	contenttypes	contenttype
6	sessions	session
7	core	subscriber
8	core	contact
9	stories	category
10	stories	story
11	stories	tag
12	stories	storyimage
13	stories	comment
\.


--
-- Data for Name: django_migrations; Type: TABLE DATA; Schema: public; Owner: food_user
--

COPY public.django_migrations (id, app, name, applied) FROM stdin;
1	contenttypes	0001_initial	2023-04-11 15:37:09.936198+00
2	auth	0001_initial	2023-04-11 15:37:10.082404+00
3	admin	0001_initial	2023-04-11 15:37:10.125605+00
4	admin	0002_logentry_remove_auto_add	2023-04-11 15:37:10.134301+00
5	admin	0003_logentry_add_action_flag_choices	2023-04-11 15:37:10.14252+00
6	contenttypes	0002_remove_content_type_name	2023-04-11 15:37:10.154991+00
7	auth	0002_alter_permission_name_max_length	2023-04-11 15:37:10.163119+00
8	auth	0003_alter_user_email_max_length	2023-04-11 15:37:10.173196+00
9	auth	0004_alter_user_username_opts	2023-04-11 15:37:10.182114+00
10	auth	0005_alter_user_last_login_null	2023-04-11 15:37:10.191621+00
11	auth	0006_require_contenttypes_0002	2023-04-11 15:37:10.195039+00
12	auth	0007_alter_validators_add_error_messages	2023-04-11 15:37:10.203762+00
13	auth	0008_alter_user_username_max_length	2023-04-11 15:37:10.219062+00
14	auth	0009_alter_user_last_name_max_length	2023-04-11 15:37:10.23842+00
15	auth	0010_alter_group_name_max_length	2023-04-11 15:37:10.248098+00
16	auth	0011_update_proxy_permissions	2023-04-11 15:37:10.257319+00
17	auth	0012_alter_user_first_name_max_length	2023-04-11 15:37:10.265511+00
18	core	0001_initial	2023-04-11 15:37:10.276631+00
19	core	0002_contact	2023-04-11 15:37:10.295529+00
20	sessions	0001_initial	2023-04-11 15:37:10.327743+00
21	stories	0001_initial	2023-04-11 15:37:10.468474+00
22	stories	0002_story_created_at	2023-04-11 15:37:10.479703+00
\.


--
-- Data for Name: django_session; Type: TABLE DATA; Schema: public; Owner: food_user
--

COPY public.django_session (session_key, session_data, expire_date) FROM stdin;
\.


--
-- Data for Name: stories_category; Type: TABLE DATA; Schema: public; Owner: food_user
--

COPY public.stories_category (id, name, background_image) FROM stdin;
\.


--
-- Data for Name: stories_comment; Type: TABLE DATA; Schema: public; Owner: food_user
--

COPY public.stories_comment (id, text, created_at, story_id, user_id) FROM stdin;
\.


--
-- Data for Name: stories_story; Type: TABLE DATA; Schema: public; Owner: food_user
--

COPY public.stories_story (id, title, description, author_id, category_id, created_at) FROM stdin;
\.


--
-- Data for Name: stories_story_tags; Type: TABLE DATA; Schema: public; Owner: food_user
--

COPY public.stories_story_tags (id, story_id, tag_id) FROM stdin;
\.


--
-- Data for Name: stories_storyimage; Type: TABLE DATA; Schema: public; Owner: food_user
--

COPY public.stories_storyimage (id, image, created_at, story_id) FROM stdin;
\.


--
-- Data for Name: stories_tag; Type: TABLE DATA; Schema: public; Owner: food_user
--

COPY public.stories_tag (id, name) FROM stdin;
\.


--
-- Name: auth_group_id_seq; Type: SEQUENCE SET; Schema: public; Owner: food_user
--

SELECT pg_catalog.setval('public.auth_group_id_seq', 1, false);


--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: food_user
--

SELECT pg_catalog.setval('public.auth_group_permissions_id_seq', 1, false);


--
-- Name: auth_permission_id_seq; Type: SEQUENCE SET; Schema: public; Owner: food_user
--

SELECT pg_catalog.setval('public.auth_permission_id_seq', 52, true);


--
-- Name: auth_user_groups_id_seq; Type: SEQUENCE SET; Schema: public; Owner: food_user
--

SELECT pg_catalog.setval('public.auth_user_groups_id_seq', 1, false);


--
-- Name: auth_user_id_seq; Type: SEQUENCE SET; Schema: public; Owner: food_user
--

SELECT pg_catalog.setval('public.auth_user_id_seq', 1, true);


--
-- Name: auth_user_user_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: food_user
--

SELECT pg_catalog.setval('public.auth_user_user_permissions_id_seq', 1, false);


--
-- Name: core_contact_id_seq; Type: SEQUENCE SET; Schema: public; Owner: food_user
--

SELECT pg_catalog.setval('public.core_contact_id_seq', 1, false);


--
-- Name: core_subscriber_id_seq; Type: SEQUENCE SET; Schema: public; Owner: food_user
--

SELECT pg_catalog.setval('public.core_subscriber_id_seq', 1, false);


--
-- Name: django_admin_log_id_seq; Type: SEQUENCE SET; Schema: public; Owner: food_user
--

SELECT pg_catalog.setval('public.django_admin_log_id_seq', 1, false);


--
-- Name: django_content_type_id_seq; Type: SEQUENCE SET; Schema: public; Owner: food_user
--

SELECT pg_catalog.setval('public.django_content_type_id_seq', 13, true);


--
-- Name: django_migrations_id_seq; Type: SEQUENCE SET; Schema: public; Owner: food_user
--

SELECT pg_catalog.setval('public.django_migrations_id_seq', 22, true);


--
-- Name: stories_category_id_seq; Type: SEQUENCE SET; Schema: public; Owner: food_user
--

SELECT pg_catalog.setval('public.stories_category_id_seq', 1, false);


--
-- Name: stories_comment_id_seq; Type: SEQUENCE SET; Schema: public; Owner: food_user
--

SELECT pg_catalog.setval('public.stories_comment_id_seq', 1, false);


--
-- Name: stories_story_id_seq; Type: SEQUENCE SET; Schema: public; Owner: food_user
--

SELECT pg_catalog.setval('public.stories_story_id_seq', 1, false);


--
-- Name: stories_story_tags_id_seq; Type: SEQUENCE SET; Schema: public; Owner: food_user
--

SELECT pg_catalog.setval('public.stories_story_tags_id_seq', 1, false);


--
-- Name: stories_storyimage_id_seq; Type: SEQUENCE SET; Schema: public; Owner: food_user
--

SELECT pg_catalog.setval('public.stories_storyimage_id_seq', 1, false);


--
-- Name: stories_tag_id_seq; Type: SEQUENCE SET; Schema: public; Owner: food_user
--

SELECT pg_catalog.setval('public.stories_tag_id_seq', 1, false);


--
-- Name: auth_group auth_group_name_key; Type: CONSTRAINT; Schema: public; Owner: food_user
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_name_key UNIQUE (name);


--
-- Name: auth_group_permissions auth_group_permissions_group_id_permission_id_0cd325b0_uniq; Type: CONSTRAINT; Schema: public; Owner: food_user
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_permission_id_0cd325b0_uniq UNIQUE (group_id, permission_id);


--
-- Name: auth_group_permissions auth_group_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: food_user
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_group auth_group_pkey; Type: CONSTRAINT; Schema: public; Owner: food_user
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_pkey PRIMARY KEY (id);


--
-- Name: auth_permission auth_permission_content_type_id_codename_01ab375a_uniq; Type: CONSTRAINT; Schema: public; Owner: food_user
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_codename_01ab375a_uniq UNIQUE (content_type_id, codename);


--
-- Name: auth_permission auth_permission_pkey; Type: CONSTRAINT; Schema: public; Owner: food_user
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_pkey PRIMARY KEY (id);


--
-- Name: auth_user_groups auth_user_groups_pkey; Type: CONSTRAINT; Schema: public; Owner: food_user
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_pkey PRIMARY KEY (id);


--
-- Name: auth_user_groups auth_user_groups_user_id_group_id_94350c0c_uniq; Type: CONSTRAINT; Schema: public; Owner: food_user
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_user_id_group_id_94350c0c_uniq UNIQUE (user_id, group_id);


--
-- Name: auth_user auth_user_pkey; Type: CONSTRAINT; Schema: public; Owner: food_user
--

ALTER TABLE ONLY public.auth_user
    ADD CONSTRAINT auth_user_pkey PRIMARY KEY (id);


--
-- Name: auth_user_user_permissions auth_user_user_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: food_user
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_user_user_permissions auth_user_user_permissions_user_id_permission_id_14a6b632_uniq; Type: CONSTRAINT; Schema: public; Owner: food_user
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_user_id_permission_id_14a6b632_uniq UNIQUE (user_id, permission_id);


--
-- Name: auth_user auth_user_username_key; Type: CONSTRAINT; Schema: public; Owner: food_user
--

ALTER TABLE ONLY public.auth_user
    ADD CONSTRAINT auth_user_username_key UNIQUE (username);


--
-- Name: core_contact core_contact_pkey; Type: CONSTRAINT; Schema: public; Owner: food_user
--

ALTER TABLE ONLY public.core_contact
    ADD CONSTRAINT core_contact_pkey PRIMARY KEY (id);


--
-- Name: core_subscriber core_subscriber_pkey; Type: CONSTRAINT; Schema: public; Owner: food_user
--

ALTER TABLE ONLY public.core_subscriber
    ADD CONSTRAINT core_subscriber_pkey PRIMARY KEY (id);


--
-- Name: django_admin_log django_admin_log_pkey; Type: CONSTRAINT; Schema: public; Owner: food_user
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_pkey PRIMARY KEY (id);


--
-- Name: django_content_type django_content_type_app_label_model_76bd3d3b_uniq; Type: CONSTRAINT; Schema: public; Owner: food_user
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_app_label_model_76bd3d3b_uniq UNIQUE (app_label, model);


--
-- Name: django_content_type django_content_type_pkey; Type: CONSTRAINT; Schema: public; Owner: food_user
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_pkey PRIMARY KEY (id);


--
-- Name: django_migrations django_migrations_pkey; Type: CONSTRAINT; Schema: public; Owner: food_user
--

ALTER TABLE ONLY public.django_migrations
    ADD CONSTRAINT django_migrations_pkey PRIMARY KEY (id);


--
-- Name: django_session django_session_pkey; Type: CONSTRAINT; Schema: public; Owner: food_user
--

ALTER TABLE ONLY public.django_session
    ADD CONSTRAINT django_session_pkey PRIMARY KEY (session_key);


--
-- Name: stories_category stories_category_pkey; Type: CONSTRAINT; Schema: public; Owner: food_user
--

ALTER TABLE ONLY public.stories_category
    ADD CONSTRAINT stories_category_pkey PRIMARY KEY (id);


--
-- Name: stories_comment stories_comment_pkey; Type: CONSTRAINT; Schema: public; Owner: food_user
--

ALTER TABLE ONLY public.stories_comment
    ADD CONSTRAINT stories_comment_pkey PRIMARY KEY (id);


--
-- Name: stories_story stories_story_pkey; Type: CONSTRAINT; Schema: public; Owner: food_user
--

ALTER TABLE ONLY public.stories_story
    ADD CONSTRAINT stories_story_pkey PRIMARY KEY (id);


--
-- Name: stories_story_tags stories_story_tags_pkey; Type: CONSTRAINT; Schema: public; Owner: food_user
--

ALTER TABLE ONLY public.stories_story_tags
    ADD CONSTRAINT stories_story_tags_pkey PRIMARY KEY (id);


--
-- Name: stories_story_tags stories_story_tags_story_id_tag_id_b53f93ac_uniq; Type: CONSTRAINT; Schema: public; Owner: food_user
--

ALTER TABLE ONLY public.stories_story_tags
    ADD CONSTRAINT stories_story_tags_story_id_tag_id_b53f93ac_uniq UNIQUE (story_id, tag_id);


--
-- Name: stories_storyimage stories_storyimage_pkey; Type: CONSTRAINT; Schema: public; Owner: food_user
--

ALTER TABLE ONLY public.stories_storyimage
    ADD CONSTRAINT stories_storyimage_pkey PRIMARY KEY (id);


--
-- Name: stories_tag stories_tag_pkey; Type: CONSTRAINT; Schema: public; Owner: food_user
--

ALTER TABLE ONLY public.stories_tag
    ADD CONSTRAINT stories_tag_pkey PRIMARY KEY (id);


--
-- Name: auth_group_name_a6ea08ec_like; Type: INDEX; Schema: public; Owner: food_user
--

CREATE INDEX auth_group_name_a6ea08ec_like ON public.auth_group USING btree (name varchar_pattern_ops);


--
-- Name: auth_group_permissions_group_id_b120cbf9; Type: INDEX; Schema: public; Owner: food_user
--

CREATE INDEX auth_group_permissions_group_id_b120cbf9 ON public.auth_group_permissions USING btree (group_id);


--
-- Name: auth_group_permissions_permission_id_84c5c92e; Type: INDEX; Schema: public; Owner: food_user
--

CREATE INDEX auth_group_permissions_permission_id_84c5c92e ON public.auth_group_permissions USING btree (permission_id);


--
-- Name: auth_permission_content_type_id_2f476e4b; Type: INDEX; Schema: public; Owner: food_user
--

CREATE INDEX auth_permission_content_type_id_2f476e4b ON public.auth_permission USING btree (content_type_id);


--
-- Name: auth_user_groups_group_id_97559544; Type: INDEX; Schema: public; Owner: food_user
--

CREATE INDEX auth_user_groups_group_id_97559544 ON public.auth_user_groups USING btree (group_id);


--
-- Name: auth_user_groups_user_id_6a12ed8b; Type: INDEX; Schema: public; Owner: food_user
--

CREATE INDEX auth_user_groups_user_id_6a12ed8b ON public.auth_user_groups USING btree (user_id);


--
-- Name: auth_user_user_permissions_permission_id_1fbb5f2c; Type: INDEX; Schema: public; Owner: food_user
--

CREATE INDEX auth_user_user_permissions_permission_id_1fbb5f2c ON public.auth_user_user_permissions USING btree (permission_id);


--
-- Name: auth_user_user_permissions_user_id_a95ead1b; Type: INDEX; Schema: public; Owner: food_user
--

CREATE INDEX auth_user_user_permissions_user_id_a95ead1b ON public.auth_user_user_permissions USING btree (user_id);


--
-- Name: auth_user_username_6821ab7c_like; Type: INDEX; Schema: public; Owner: food_user
--

CREATE INDEX auth_user_username_6821ab7c_like ON public.auth_user USING btree (username varchar_pattern_ops);


--
-- Name: django_admin_log_content_type_id_c4bce8eb; Type: INDEX; Schema: public; Owner: food_user
--

CREATE INDEX django_admin_log_content_type_id_c4bce8eb ON public.django_admin_log USING btree (content_type_id);


--
-- Name: django_admin_log_user_id_c564eba6; Type: INDEX; Schema: public; Owner: food_user
--

CREATE INDEX django_admin_log_user_id_c564eba6 ON public.django_admin_log USING btree (user_id);


--
-- Name: django_session_expire_date_a5c62663; Type: INDEX; Schema: public; Owner: food_user
--

CREATE INDEX django_session_expire_date_a5c62663 ON public.django_session USING btree (expire_date);


--
-- Name: django_session_session_key_c0390e0f_like; Type: INDEX; Schema: public; Owner: food_user
--

CREATE INDEX django_session_session_key_c0390e0f_like ON public.django_session USING btree (session_key varchar_pattern_ops);


--
-- Name: stories_comment_story_id_5f9b1bc1; Type: INDEX; Schema: public; Owner: food_user
--

CREATE INDEX stories_comment_story_id_5f9b1bc1 ON public.stories_comment USING btree (story_id);


--
-- Name: stories_comment_user_id_2ac9b492; Type: INDEX; Schema: public; Owner: food_user
--

CREATE INDEX stories_comment_user_id_2ac9b492 ON public.stories_comment USING btree (user_id);


--
-- Name: stories_story_author_id_8dbbe77a; Type: INDEX; Schema: public; Owner: food_user
--

CREATE INDEX stories_story_author_id_8dbbe77a ON public.stories_story USING btree (author_id);


--
-- Name: stories_story_category_id_8381703d; Type: INDEX; Schema: public; Owner: food_user
--

CREATE INDEX stories_story_category_id_8381703d ON public.stories_story USING btree (category_id);


--
-- Name: stories_story_tags_story_id_23f247f5; Type: INDEX; Schema: public; Owner: food_user
--

CREATE INDEX stories_story_tags_story_id_23f247f5 ON public.stories_story_tags USING btree (story_id);


--
-- Name: stories_story_tags_tag_id_191e51a8; Type: INDEX; Schema: public; Owner: food_user
--

CREATE INDEX stories_story_tags_tag_id_191e51a8 ON public.stories_story_tags USING btree (tag_id);


--
-- Name: stories_storyimage_story_id_ca40867d; Type: INDEX; Schema: public; Owner: food_user
--

CREATE INDEX stories_storyimage_story_id_ca40867d ON public.stories_storyimage USING btree (story_id);


--
-- Name: auth_group_permissions auth_group_permissio_permission_id_84c5c92e_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: food_user
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissio_permission_id_84c5c92e_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_group_permissions auth_group_permissions_group_id_b120cbf9_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: food_user
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_b120cbf9_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_permission auth_permission_content_type_id_2f476e4b_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: food_user
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_2f476e4b_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_groups auth_user_groups_group_id_97559544_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: food_user
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_group_id_97559544_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_groups auth_user_groups_user_id_6a12ed8b_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: food_user
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_user_id_6a12ed8b_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_user_permissions auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: food_user
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_user_permissions auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: food_user
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_content_type_id_c4bce8eb_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: food_user
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_content_type_id_c4bce8eb_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_user_id_c564eba6_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: food_user
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_user_id_c564eba6_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: stories_comment stories_comment_story_id_5f9b1bc1_fk_stories_story_id; Type: FK CONSTRAINT; Schema: public; Owner: food_user
--

ALTER TABLE ONLY public.stories_comment
    ADD CONSTRAINT stories_comment_story_id_5f9b1bc1_fk_stories_story_id FOREIGN KEY (story_id) REFERENCES public.stories_story(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: stories_comment stories_comment_user_id_2ac9b492_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: food_user
--

ALTER TABLE ONLY public.stories_comment
    ADD CONSTRAINT stories_comment_user_id_2ac9b492_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: stories_story stories_story_author_id_8dbbe77a_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: food_user
--

ALTER TABLE ONLY public.stories_story
    ADD CONSTRAINT stories_story_author_id_8dbbe77a_fk_auth_user_id FOREIGN KEY (author_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: stories_story stories_story_category_id_8381703d_fk_stories_category_id; Type: FK CONSTRAINT; Schema: public; Owner: food_user
--

ALTER TABLE ONLY public.stories_story
    ADD CONSTRAINT stories_story_category_id_8381703d_fk_stories_category_id FOREIGN KEY (category_id) REFERENCES public.stories_category(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: stories_story_tags stories_story_tags_story_id_23f247f5_fk_stories_story_id; Type: FK CONSTRAINT; Schema: public; Owner: food_user
--

ALTER TABLE ONLY public.stories_story_tags
    ADD CONSTRAINT stories_story_tags_story_id_23f247f5_fk_stories_story_id FOREIGN KEY (story_id) REFERENCES public.stories_story(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: stories_story_tags stories_story_tags_tag_id_191e51a8_fk_stories_tag_id; Type: FK CONSTRAINT; Schema: public; Owner: food_user
--

ALTER TABLE ONLY public.stories_story_tags
    ADD CONSTRAINT stories_story_tags_tag_id_191e51a8_fk_stories_tag_id FOREIGN KEY (tag_id) REFERENCES public.stories_tag(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: stories_storyimage stories_storyimage_story_id_ca40867d_fk_stories_story_id; Type: FK CONSTRAINT; Schema: public; Owner: food_user
--

ALTER TABLE ONLY public.stories_storyimage
    ADD CONSTRAINT stories_storyimage_story_id_ca40867d_fk_stories_story_id FOREIGN KEY (story_id) REFERENCES public.stories_story(id) DEFERRABLE INITIALLY DEFERRED;


--
-- PostgreSQL database dump complete
--

--
-- PostgreSQL database dump
--

-- Dumped from database version 15.1 (Debian 15.1-1.pgdg110+1)
-- Dumped by pg_dump version 15.1 (Debian 15.1-1.pgdg110+1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: auth_group; Type: TABLE; Schema: public; Owner: food_user
--

CREATE TABLE public.auth_group (
    id integer NOT NULL,
    name character varying(150) NOT NULL
);


ALTER TABLE public.auth_group OWNER TO food_user;

--
-- Name: auth_group_id_seq; Type: SEQUENCE; Schema: public; Owner: food_user
--

ALTER TABLE public.auth_group ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_group_permissions; Type: TABLE; Schema: public; Owner: food_user
--

CREATE TABLE public.auth_group_permissions (
    id bigint NOT NULL,
    group_id integer NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.auth_group_permissions OWNER TO food_user;

--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: food_user
--

ALTER TABLE public.auth_group_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_permission; Type: TABLE; Schema: public; Owner: food_user
--

CREATE TABLE public.auth_permission (
    id integer NOT NULL,
    name character varying(255) NOT NULL,
    content_type_id integer NOT NULL,
    codename character varying(100) NOT NULL
);


ALTER TABLE public.auth_permission OWNER TO food_user;

--
-- Name: auth_permission_id_seq; Type: SEQUENCE; Schema: public; Owner: food_user
--

ALTER TABLE public.auth_permission ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_permission_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user; Type: TABLE; Schema: public; Owner: food_user
--

CREATE TABLE public.auth_user (
    id integer NOT NULL,
    password character varying(128) NOT NULL,
    last_login timestamp with time zone,
    is_superuser boolean NOT NULL,
    username character varying(150) NOT NULL,
    first_name character varying(150) NOT NULL,
    last_name character varying(150) NOT NULL,
    email character varying(254) NOT NULL,
    is_staff boolean NOT NULL,
    is_active boolean NOT NULL,
    date_joined timestamp with time zone NOT NULL
);


ALTER TABLE public.auth_user OWNER TO food_user;

--
-- Name: auth_user_groups; Type: TABLE; Schema: public; Owner: food_user
--

CREATE TABLE public.auth_user_groups (
    id bigint NOT NULL,
    user_id integer NOT NULL,
    group_id integer NOT NULL
);


ALTER TABLE public.auth_user_groups OWNER TO food_user;

--
-- Name: auth_user_groups_id_seq; Type: SEQUENCE; Schema: public; Owner: food_user
--

ALTER TABLE public.auth_user_groups ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_groups_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user_id_seq; Type: SEQUENCE; Schema: public; Owner: food_user
--

ALTER TABLE public.auth_user ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user_user_permissions; Type: TABLE; Schema: public; Owner: food_user
--

CREATE TABLE public.auth_user_user_permissions (
    id bigint NOT NULL,
    user_id integer NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.auth_user_user_permissions OWNER TO food_user;

--
-- Name: auth_user_user_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: food_user
--

ALTER TABLE public.auth_user_user_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_user_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: core_contact; Type: TABLE; Schema: public; Owner: food_user
--

CREATE TABLE public.core_contact (
    id bigint NOT NULL,
    name character varying(50) NOT NULL,
    email character varying(254) NOT NULL,
    subject character varying(255) NOT NULL,
    message text NOT NULL,
    created_at timestamp with time zone NOT NULL
);


ALTER TABLE public.core_contact OWNER TO food_user;

--
-- Name: core_contact_id_seq; Type: SEQUENCE; Schema: public; Owner: food_user
--

ALTER TABLE public.core_contact ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.core_contact_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: core_subscriber; Type: TABLE; Schema: public; Owner: food_user
--

CREATE TABLE public.core_subscriber (
    id bigint NOT NULL,
    email character varying(254) NOT NULL,
    is_active boolean NOT NULL,
    created_at timestamp with time zone NOT NULL
);


ALTER TABLE public.core_subscriber OWNER TO food_user;

--
-- Name: core_subscriber_id_seq; Type: SEQUENCE; Schema: public; Owner: food_user
--

ALTER TABLE public.core_subscriber ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.core_subscriber_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_admin_log; Type: TABLE; Schema: public; Owner: food_user
--

CREATE TABLE public.django_admin_log (
    id integer NOT NULL,
    action_time timestamp with time zone NOT NULL,
    object_id text,
    object_repr character varying(200) NOT NULL,
    action_flag smallint NOT NULL,
    change_message text NOT NULL,
    content_type_id integer,
    user_id integer NOT NULL,
    CONSTRAINT django_admin_log_action_flag_check CHECK ((action_flag >= 0))
);


ALTER TABLE public.django_admin_log OWNER TO food_user;

--
-- Name: django_admin_log_id_seq; Type: SEQUENCE; Schema: public; Owner: food_user
--

ALTER TABLE public.django_admin_log ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_admin_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_content_type; Type: TABLE; Schema: public; Owner: food_user
--

CREATE TABLE public.django_content_type (
    id integer NOT NULL,
    app_label character varying(100) NOT NULL,
    model character varying(100) NOT NULL
);


ALTER TABLE public.django_content_type OWNER TO food_user;

--
-- Name: django_content_type_id_seq; Type: SEQUENCE; Schema: public; Owner: food_user
--

ALTER TABLE public.django_content_type ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_content_type_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_migrations; Type: TABLE; Schema: public; Owner: food_user
--

CREATE TABLE public.django_migrations (
    id bigint NOT NULL,
    app character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    applied timestamp with time zone NOT NULL
);


ALTER TABLE public.django_migrations OWNER TO food_user;

--
-- Name: django_migrations_id_seq; Type: SEQUENCE; Schema: public; Owner: food_user
--

ALTER TABLE public.django_migrations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_migrations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_session; Type: TABLE; Schema: public; Owner: food_user
--

CREATE TABLE public.django_session (
    session_key character varying(40) NOT NULL,
    session_data text NOT NULL,
    expire_date timestamp with time zone NOT NULL
);


ALTER TABLE public.django_session OWNER TO food_user;

--
-- Name: stories_category; Type: TABLE; Schema: public; Owner: food_user
--

CREATE TABLE public.stories_category (
    id bigint NOT NULL,
    name character varying(20) NOT NULL,
    background_image character varying(100) NOT NULL
);


ALTER TABLE public.stories_category OWNER TO food_user;

--
-- Name: stories_category_id_seq; Type: SEQUENCE; Schema: public; Owner: food_user
--

ALTER TABLE public.stories_category ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.stories_category_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: stories_comment; Type: TABLE; Schema: public; Owner: food_user
--

CREATE TABLE public.stories_comment (
    id bigint NOT NULL,
    text text NOT NULL,
    created_at timestamp with time zone NOT NULL,
    story_id bigint NOT NULL,
    user_id integer NOT NULL
);


ALTER TABLE public.stories_comment OWNER TO food_user;

--
-- Name: stories_comment_id_seq; Type: SEQUENCE; Schema: public; Owner: food_user
--

ALTER TABLE public.stories_comment ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.stories_comment_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: stories_story; Type: TABLE; Schema: public; Owner: food_user
--

CREATE TABLE public.stories_story (
    id bigint NOT NULL,
    title character varying(250) NOT NULL,
    description text NOT NULL,
    author_id integer NOT NULL,
    category_id bigint NOT NULL,
    created_at timestamp with time zone NOT NULL
);


ALTER TABLE public.stories_story OWNER TO food_user;

--
-- Name: stories_story_id_seq; Type: SEQUENCE; Schema: public; Owner: food_user
--

ALTER TABLE public.stories_story ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.stories_story_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: stories_story_tags; Type: TABLE; Schema: public; Owner: food_user
--

CREATE TABLE public.stories_story_tags (
    id bigint NOT NULL,
    story_id bigint NOT NULL,
    tag_id bigint NOT NULL
);


ALTER TABLE public.stories_story_tags OWNER TO food_user;

--
-- Name: stories_story_tags_id_seq; Type: SEQUENCE; Schema: public; Owner: food_user
--

ALTER TABLE public.stories_story_tags ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.stories_story_tags_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: stories_storyimage; Type: TABLE; Schema: public; Owner: food_user
--

CREATE TABLE public.stories_storyimage (
    id bigint NOT NULL,
    image character varying(100) NOT NULL,
    created_at timestamp with time zone NOT NULL,
    story_id bigint NOT NULL
);


ALTER TABLE public.stories_storyimage OWNER TO food_user;

--
-- Name: stories_storyimage_id_seq; Type: SEQUENCE; Schema: public; Owner: food_user
--

ALTER TABLE public.stories_storyimage ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.stories_storyimage_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: stories_tag; Type: TABLE; Schema: public; Owner: food_user
--

CREATE TABLE public.stories_tag (
    id bigint NOT NULL,
    name character varying(20) NOT NULL
);


ALTER TABLE public.stories_tag OWNER TO food_user;

--
-- Name: stories_tag_id_seq; Type: SEQUENCE; Schema: public; Owner: food_user
--

ALTER TABLE public.stories_tag ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.stories_tag_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: auth_group; Type: TABLE DATA; Schema: public; Owner: food_user
--

COPY public.auth_group (id, name) FROM stdin;
\.


--
-- Data for Name: auth_group_permissions; Type: TABLE DATA; Schema: public; Owner: food_user
--

COPY public.auth_group_permissions (id, group_id, permission_id) FROM stdin;
\.


--
-- Data for Name: auth_permission; Type: TABLE DATA; Schema: public; Owner: food_user
--

COPY public.auth_permission (id, name, content_type_id, codename) FROM stdin;
1	Can add log entry	1	add_logentry
2	Can change log entry	1	change_logentry
3	Can delete log entry	1	delete_logentry
4	Can view log entry	1	view_logentry
5	Can add permission	2	add_permission
6	Can change permission	2	change_permission
7	Can delete permission	2	delete_permission
8	Can view permission	2	view_permission
9	Can add group	3	add_group
10	Can change group	3	change_group
11	Can delete group	3	delete_group
12	Can view group	3	view_group
13	Can add user	4	add_user
14	Can change user	4	change_user
15	Can delete user	4	delete_user
16	Can view user	4	view_user
17	Can add content type	5	add_contenttype
18	Can change content type	5	change_contenttype
19	Can delete content type	5	delete_contenttype
20	Can view content type	5	view_contenttype
21	Can add session	6	add_session
22	Can change session	6	change_session
23	Can delete session	6	delete_session
24	Can view session	6	view_session
25	Can add subscriber	7	add_subscriber
26	Can change subscriber	7	change_subscriber
27	Can delete subscriber	7	delete_subscriber
28	Can view subscriber	7	view_subscriber
29	Can add contact	8	add_contact
30	Can change contact	8	change_contact
31	Can delete contact	8	delete_contact
32	Can view contact	8	view_contact
33	Can add category	9	add_category
34	Can change category	9	change_category
35	Can delete category	9	delete_category
36	Can view category	9	view_category
37	Can add story	10	add_story
38	Can change story	10	change_story
39	Can delete story	10	delete_story
40	Can view story	10	view_story
41	Can add tag	11	add_tag
42	Can change tag	11	change_tag
43	Can delete tag	11	delete_tag
44	Can view tag	11	view_tag
45	Can add story image	12	add_storyimage
46	Can change story image	12	change_storyimage
47	Can delete story image	12	delete_storyimage
48	Can view story image	12	view_storyimage
49	Can add comment	13	add_comment
50	Can change comment	13	change_comment
51	Can delete comment	13	delete_comment
52	Can view comment	13	view_comment
\.


--
-- Data for Name: auth_user; Type: TABLE DATA; Schema: public; Owner: food_user
--

COPY public.auth_user (id, password, last_login, is_superuser, username, first_name, last_name, email, is_staff, is_active, date_joined) FROM stdin;
1	pbkdf2_sha256$390000$LEFFXHmza56TSBJGplTntL$evmqsaq7X/Ro95SGNDnZ8j7OA8Sn8D/Z80DJtS09bgc=	\N	t	elnur				t	t	2023-04-11 15:38:44.551497+00
\.


--
-- Data for Name: auth_user_groups; Type: TABLE DATA; Schema: public; Owner: food_user
--

COPY public.auth_user_groups (id, user_id, group_id) FROM stdin;
\.


--
-- Data for Name: auth_user_user_permissions; Type: TABLE DATA; Schema: public; Owner: food_user
--

COPY public.auth_user_user_permissions (id, user_id, permission_id) FROM stdin;
\.


--
-- Data for Name: core_contact; Type: TABLE DATA; Schema: public; Owner: food_user
--

COPY public.core_contact (id, name, email, subject, message, created_at) FROM stdin;
\.


--
-- Data for Name: core_subscriber; Type: TABLE DATA; Schema: public; Owner: food_user
--

COPY public.core_subscriber (id, email, is_active, created_at) FROM stdin;
\.


--
-- Data for Name: django_admin_log; Type: TABLE DATA; Schema: public; Owner: food_user
--

COPY public.django_admin_log (id, action_time, object_id, object_repr, action_flag, change_message, content_type_id, user_id) FROM stdin;
\.


--
-- Data for Name: django_content_type; Type: TABLE DATA; Schema: public; Owner: food_user
--

COPY public.django_content_type (id, app_label, model) FROM stdin;
1	admin	logentry
2	auth	permission
3	auth	group
4	auth	user
5	contenttypes	contenttype
6	sessions	session
7	core	subscriber
8	core	contact
9	stories	category
10	stories	story
11	stories	tag
12	stories	storyimage
13	stories	comment
\.


--
-- Data for Name: django_migrations; Type: TABLE DATA; Schema: public; Owner: food_user
--

COPY public.django_migrations (id, app, name, applied) FROM stdin;
1	contenttypes	0001_initial	2023-04-11 15:37:09.936198+00
2	auth	0001_initial	2023-04-11 15:37:10.082404+00
3	admin	0001_initial	2023-04-11 15:37:10.125605+00
4	admin	0002_logentry_remove_auto_add	2023-04-11 15:37:10.134301+00
5	admin	0003_logentry_add_action_flag_choices	2023-04-11 15:37:10.14252+00
6	contenttypes	0002_remove_content_type_name	2023-04-11 15:37:10.154991+00
7	auth	0002_alter_permission_name_max_length	2023-04-11 15:37:10.163119+00
8	auth	0003_alter_user_email_max_length	2023-04-11 15:37:10.173196+00
9	auth	0004_alter_user_username_opts	2023-04-11 15:37:10.182114+00
10	auth	0005_alter_user_last_login_null	2023-04-11 15:37:10.191621+00
11	auth	0006_require_contenttypes_0002	2023-04-11 15:37:10.195039+00
12	auth	0007_alter_validators_add_error_messages	2023-04-11 15:37:10.203762+00
13	auth	0008_alter_user_username_max_length	2023-04-11 15:37:10.219062+00
14	auth	0009_alter_user_last_name_max_length	2023-04-11 15:37:10.23842+00
15	auth	0010_alter_group_name_max_length	2023-04-11 15:37:10.248098+00
16	auth	0011_update_proxy_permissions	2023-04-11 15:37:10.257319+00
17	auth	0012_alter_user_first_name_max_length	2023-04-11 15:37:10.265511+00
18	core	0001_initial	2023-04-11 15:37:10.276631+00
19	core	0002_contact	2023-04-11 15:37:10.295529+00
20	sessions	0001_initial	2023-04-11 15:37:10.327743+00
21	stories	0001_initial	2023-04-11 15:37:10.468474+00
22	stories	0002_story_created_at	2023-04-11 15:37:10.479703+00
\.


--
-- Data for Name: django_session; Type: TABLE DATA; Schema: public; Owner: food_user
--

COPY public.django_session (session_key, session_data, expire_date) FROM stdin;
\.


--
-- Data for Name: stories_category; Type: TABLE DATA; Schema: public; Owner: food_user
--

COPY public.stories_category (id, name, background_image) FROM stdin;
\.


--
-- Data for Name: stories_comment; Type: TABLE DATA; Schema: public; Owner: food_user
--

COPY public.stories_comment (id, text, created_at, story_id, user_id) FROM stdin;
\.


--
-- Data for Name: stories_story; Type: TABLE DATA; Schema: public; Owner: food_user
--

COPY public.stories_story (id, title, description, author_id, category_id, created_at) FROM stdin;
\.


--
-- Data for Name: stories_story_tags; Type: TABLE DATA; Schema: public; Owner: food_user
--

COPY public.stories_story_tags (id, story_id, tag_id) FROM stdin;
\.


--
-- Data for Name: stories_storyimage; Type: TABLE DATA; Schema: public; Owner: food_user
--

COPY public.stories_storyimage (id, image, created_at, story_id) FROM stdin;
\.


--
-- Data for Name: stories_tag; Type: TABLE DATA; Schema: public; Owner: food_user
--

COPY public.stories_tag (id, name) FROM stdin;
\.


--
-- Name: auth_group_id_seq; Type: SEQUENCE SET; Schema: public; Owner: food_user
--

SELECT pg_catalog.setval('public.auth_group_id_seq', 1, false);


--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: food_user
--

SELECT pg_catalog.setval('public.auth_group_permissions_id_seq', 1, false);


--
-- Name: auth_permission_id_seq; Type: SEQUENCE SET; Schema: public; Owner: food_user
--

SELECT pg_catalog.setval('public.auth_permission_id_seq', 52, true);


--
-- Name: auth_user_groups_id_seq; Type: SEQUENCE SET; Schema: public; Owner: food_user
--

SELECT pg_catalog.setval('public.auth_user_groups_id_seq', 1, false);


--
-- Name: auth_user_id_seq; Type: SEQUENCE SET; Schema: public; Owner: food_user
--

SELECT pg_catalog.setval('public.auth_user_id_seq', 1, true);


--
-- Name: auth_user_user_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: food_user
--

SELECT pg_catalog.setval('public.auth_user_user_permissions_id_seq', 1, false);


--
-- Name: core_contact_id_seq; Type: SEQUENCE SET; Schema: public; Owner: food_user
--

SELECT pg_catalog.setval('public.core_contact_id_seq', 1, false);


--
-- Name: core_subscriber_id_seq; Type: SEQUENCE SET; Schema: public; Owner: food_user
--

SELECT pg_catalog.setval('public.core_subscriber_id_seq', 1, false);


--
-- Name: django_admin_log_id_seq; Type: SEQUENCE SET; Schema: public; Owner: food_user
--

SELECT pg_catalog.setval('public.django_admin_log_id_seq', 1, false);


--
-- Name: django_content_type_id_seq; Type: SEQUENCE SET; Schema: public; Owner: food_user
--

SELECT pg_catalog.setval('public.django_content_type_id_seq', 13, true);


--
-- Name: django_migrations_id_seq; Type: SEQUENCE SET; Schema: public; Owner: food_user
--

SELECT pg_catalog.setval('public.django_migrations_id_seq', 22, true);


--
-- Name: stories_category_id_seq; Type: SEQUENCE SET; Schema: public; Owner: food_user
--

SELECT pg_catalog.setval('public.stories_category_id_seq', 1, false);


--
-- Name: stories_comment_id_seq; Type: SEQUENCE SET; Schema: public; Owner: food_user
--

SELECT pg_catalog.setval('public.stories_comment_id_seq', 1, false);


--
-- Name: stories_story_id_seq; Type: SEQUENCE SET; Schema: public; Owner: food_user
--

SELECT pg_catalog.setval('public.stories_story_id_seq', 1, false);


--
-- Name: stories_story_tags_id_seq; Type: SEQUENCE SET; Schema: public; Owner: food_user
--

SELECT pg_catalog.setval('public.stories_story_tags_id_seq', 1, false);


--
-- Name: stories_storyimage_id_seq; Type: SEQUENCE SET; Schema: public; Owner: food_user
--

SELECT pg_catalog.setval('public.stories_storyimage_id_seq', 1, false);


--
-- Name: stories_tag_id_seq; Type: SEQUENCE SET; Schema: public; Owner: food_user
--

SELECT pg_catalog.setval('public.stories_tag_id_seq', 1, false);


--
-- Name: auth_group auth_group_name_key; Type: CONSTRAINT; Schema: public; Owner: food_user
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_name_key UNIQUE (name);


--
-- Name: auth_group_permissions auth_group_permissions_group_id_permission_id_0cd325b0_uniq; Type: CONSTRAINT; Schema: public; Owner: food_user
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_permission_id_0cd325b0_uniq UNIQUE (group_id, permission_id);


--
-- Name: auth_group_permissions auth_group_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: food_user
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_group auth_group_pkey; Type: CONSTRAINT; Schema: public; Owner: food_user
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_pkey PRIMARY KEY (id);


--
-- Name: auth_permission auth_permission_content_type_id_codename_01ab375a_uniq; Type: CONSTRAINT; Schema: public; Owner: food_user
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_codename_01ab375a_uniq UNIQUE (content_type_id, codename);


--
-- Name: auth_permission auth_permission_pkey; Type: CONSTRAINT; Schema: public; Owner: food_user
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_pkey PRIMARY KEY (id);


--
-- Name: auth_user_groups auth_user_groups_pkey; Type: CONSTRAINT; Schema: public; Owner: food_user
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_pkey PRIMARY KEY (id);


--
-- Name: auth_user_groups auth_user_groups_user_id_group_id_94350c0c_uniq; Type: CONSTRAINT; Schema: public; Owner: food_user
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_user_id_group_id_94350c0c_uniq UNIQUE (user_id, group_id);


--
-- Name: auth_user auth_user_pkey; Type: CONSTRAINT; Schema: public; Owner: food_user
--

ALTER TABLE ONLY public.auth_user
    ADD CONSTRAINT auth_user_pkey PRIMARY KEY (id);


--
-- Name: auth_user_user_permissions auth_user_user_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: food_user
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_user_user_permissions auth_user_user_permissions_user_id_permission_id_14a6b632_uniq; Type: CONSTRAINT; Schema: public; Owner: food_user
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_user_id_permission_id_14a6b632_uniq UNIQUE (user_id, permission_id);


--
-- Name: auth_user auth_user_username_key; Type: CONSTRAINT; Schema: public; Owner: food_user
--

ALTER TABLE ONLY public.auth_user
    ADD CONSTRAINT auth_user_username_key UNIQUE (username);


--
-- Name: core_contact core_contact_pkey; Type: CONSTRAINT; Schema: public; Owner: food_user
--

ALTER TABLE ONLY public.core_contact
    ADD CONSTRAINT core_contact_pkey PRIMARY KEY (id);


--
-- Name: core_subscriber core_subscriber_pkey; Type: CONSTRAINT; Schema: public; Owner: food_user
--

ALTER TABLE ONLY public.core_subscriber
    ADD CONSTRAINT core_subscriber_pkey PRIMARY KEY (id);


--
-- Name: django_admin_log django_admin_log_pkey; Type: CONSTRAINT; Schema: public; Owner: food_user
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_pkey PRIMARY KEY (id);


--
-- Name: django_content_type django_content_type_app_label_model_76bd3d3b_uniq; Type: CONSTRAINT; Schema: public; Owner: food_user
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_app_label_model_76bd3d3b_uniq UNIQUE (app_label, model);


--
-- Name: django_content_type django_content_type_pkey; Type: CONSTRAINT; Schema: public; Owner: food_user
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_pkey PRIMARY KEY (id);


--
-- Name: django_migrations django_migrations_pkey; Type: CONSTRAINT; Schema: public; Owner: food_user
--

ALTER TABLE ONLY public.django_migrations
    ADD CONSTRAINT django_migrations_pkey PRIMARY KEY (id);


--
-- Name: django_session django_session_pkey; Type: CONSTRAINT; Schema: public; Owner: food_user
--

ALTER TABLE ONLY public.django_session
    ADD CONSTRAINT django_session_pkey PRIMARY KEY (session_key);


--
-- Name: stories_category stories_category_pkey; Type: CONSTRAINT; Schema: public; Owner: food_user
--

ALTER TABLE ONLY public.stories_category
    ADD CONSTRAINT stories_category_pkey PRIMARY KEY (id);


--
-- Name: stories_comment stories_comment_pkey; Type: CONSTRAINT; Schema: public; Owner: food_user
--

ALTER TABLE ONLY public.stories_comment
    ADD CONSTRAINT stories_comment_pkey PRIMARY KEY (id);


--
-- Name: stories_story stories_story_pkey; Type: CONSTRAINT; Schema: public; Owner: food_user
--

ALTER TABLE ONLY public.stories_story
    ADD CONSTRAINT stories_story_pkey PRIMARY KEY (id);


--
-- Name: stories_story_tags stories_story_tags_pkey; Type: CONSTRAINT; Schema: public; Owner: food_user
--

ALTER TABLE ONLY public.stories_story_tags
    ADD CONSTRAINT stories_story_tags_pkey PRIMARY KEY (id);


--
-- Name: stories_story_tags stories_story_tags_story_id_tag_id_b53f93ac_uniq; Type: CONSTRAINT; Schema: public; Owner: food_user
--

ALTER TABLE ONLY public.stories_story_tags
    ADD CONSTRAINT stories_story_tags_story_id_tag_id_b53f93ac_uniq UNIQUE (story_id, tag_id);


--
-- Name: stories_storyimage stories_storyimage_pkey; Type: CONSTRAINT; Schema: public; Owner: food_user
--

ALTER TABLE ONLY public.stories_storyimage
    ADD CONSTRAINT stories_storyimage_pkey PRIMARY KEY (id);


--
-- Name: stories_tag stories_tag_pkey; Type: CONSTRAINT; Schema: public; Owner: food_user
--

ALTER TABLE ONLY public.stories_tag
    ADD CONSTRAINT stories_tag_pkey PRIMARY KEY (id);


--
-- Name: auth_group_name_a6ea08ec_like; Type: INDEX; Schema: public; Owner: food_user
--

CREATE INDEX auth_group_name_a6ea08ec_like ON public.auth_group USING btree (name varchar_pattern_ops);


--
-- Name: auth_group_permissions_group_id_b120cbf9; Type: INDEX; Schema: public; Owner: food_user
--

CREATE INDEX auth_group_permissions_group_id_b120cbf9 ON public.auth_group_permissions USING btree (group_id);


--
-- Name: auth_group_permissions_permission_id_84c5c92e; Type: INDEX; Schema: public; Owner: food_user
--

CREATE INDEX auth_group_permissions_permission_id_84c5c92e ON public.auth_group_permissions USING btree (permission_id);


--
-- Name: auth_permission_content_type_id_2f476e4b; Type: INDEX; Schema: public; Owner: food_user
--

CREATE INDEX auth_permission_content_type_id_2f476e4b ON public.auth_permission USING btree (content_type_id);


--
-- Name: auth_user_groups_group_id_97559544; Type: INDEX; Schema: public; Owner: food_user
--

CREATE INDEX auth_user_groups_group_id_97559544 ON public.auth_user_groups USING btree (group_id);


--
-- Name: auth_user_groups_user_id_6a12ed8b; Type: INDEX; Schema: public; Owner: food_user
--

CREATE INDEX auth_user_groups_user_id_6a12ed8b ON public.auth_user_groups USING btree (user_id);


--
-- Name: auth_user_user_permissions_permission_id_1fbb5f2c; Type: INDEX; Schema: public; Owner: food_user
--

CREATE INDEX auth_user_user_permissions_permission_id_1fbb5f2c ON public.auth_user_user_permissions USING btree (permission_id);


--
-- Name: auth_user_user_permissions_user_id_a95ead1b; Type: INDEX; Schema: public; Owner: food_user
--

CREATE INDEX auth_user_user_permissions_user_id_a95ead1b ON public.auth_user_user_permissions USING btree (user_id);


--
-- Name: auth_user_username_6821ab7c_like; Type: INDEX; Schema: public; Owner: food_user
--

CREATE INDEX auth_user_username_6821ab7c_like ON public.auth_user USING btree (username varchar_pattern_ops);


--
-- Name: django_admin_log_content_type_id_c4bce8eb; Type: INDEX; Schema: public; Owner: food_user
--

CREATE INDEX django_admin_log_content_type_id_c4bce8eb ON public.django_admin_log USING btree (content_type_id);


--
-- Name: django_admin_log_user_id_c564eba6; Type: INDEX; Schema: public; Owner: food_user
--

CREATE INDEX django_admin_log_user_id_c564eba6 ON public.django_admin_log USING btree (user_id);


--
-- Name: django_session_expire_date_a5c62663; Type: INDEX; Schema: public; Owner: food_user
--

CREATE INDEX django_session_expire_date_a5c62663 ON public.django_session USING btree (expire_date);


--
-- Name: django_session_session_key_c0390e0f_like; Type: INDEX; Schema: public; Owner: food_user
--

CREATE INDEX django_session_session_key_c0390e0f_like ON public.django_session USING btree (session_key varchar_pattern_ops);


--
-- Name: stories_comment_story_id_5f9b1bc1; Type: INDEX; Schema: public; Owner: food_user
--

CREATE INDEX stories_comment_story_id_5f9b1bc1 ON public.stories_comment USING btree (story_id);


--
-- Name: stories_comment_user_id_2ac9b492; Type: INDEX; Schema: public; Owner: food_user
--

CREATE INDEX stories_comment_user_id_2ac9b492 ON public.stories_comment USING btree (user_id);


--
-- Name: stories_story_author_id_8dbbe77a; Type: INDEX; Schema: public; Owner: food_user
--

CREATE INDEX stories_story_author_id_8dbbe77a ON public.stories_story USING btree (author_id);


--
-- Name: stories_story_category_id_8381703d; Type: INDEX; Schema: public; Owner: food_user
--

CREATE INDEX stories_story_category_id_8381703d ON public.stories_story USING btree (category_id);


--
-- Name: stories_story_tags_story_id_23f247f5; Type: INDEX; Schema: public; Owner: food_user
--

CREATE INDEX stories_story_tags_story_id_23f247f5 ON public.stories_story_tags USING btree (story_id);


--
-- Name: stories_story_tags_tag_id_191e51a8; Type: INDEX; Schema: public; Owner: food_user
--

CREATE INDEX stories_story_tags_tag_id_191e51a8 ON public.stories_story_tags USING btree (tag_id);


--
-- Name: stories_storyimage_story_id_ca40867d; Type: INDEX; Schema: public; Owner: food_user
--

CREATE INDEX stories_storyimage_story_id_ca40867d ON public.stories_storyimage USING btree (story_id);


--
-- Name: auth_group_permissions auth_group_permissio_permission_id_84c5c92e_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: food_user
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissio_permission_id_84c5c92e_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_group_permissions auth_group_permissions_group_id_b120cbf9_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: food_user
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_b120cbf9_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_permission auth_permission_content_type_id_2f476e4b_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: food_user
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_2f476e4b_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_groups auth_user_groups_group_id_97559544_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: food_user
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_group_id_97559544_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_groups auth_user_groups_user_id_6a12ed8b_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: food_user
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_user_id_6a12ed8b_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_user_permissions auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: food_user
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_user_permissions auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: food_user
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_content_type_id_c4bce8eb_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: food_user
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_content_type_id_c4bce8eb_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_user_id_c564eba6_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: food_user
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_user_id_c564eba6_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: stories_comment stories_comment_story_id_5f9b1bc1_fk_stories_story_id; Type: FK CONSTRAINT; Schema: public; Owner: food_user
--

ALTER TABLE ONLY public.stories_comment
    ADD CONSTRAINT stories_comment_story_id_5f9b1bc1_fk_stories_story_id FOREIGN KEY (story_id) REFERENCES public.stories_story(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: stories_comment stories_comment_user_id_2ac9b492_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: food_user
--

ALTER TABLE ONLY public.stories_comment
    ADD CONSTRAINT stories_comment_user_id_2ac9b492_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: stories_story stories_story_author_id_8dbbe77a_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: food_user
--

ALTER TABLE ONLY public.stories_story
    ADD CONSTRAINT stories_story_author_id_8dbbe77a_fk_auth_user_id FOREIGN KEY (author_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: stories_story stories_story_category_id_8381703d_fk_stories_category_id; Type: FK CONSTRAINT; Schema: public; Owner: food_user
--

ALTER TABLE ONLY public.stories_story
    ADD CONSTRAINT stories_story_category_id_8381703d_fk_stories_category_id FOREIGN KEY (category_id) REFERENCES public.stories_category(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: stories_story_tags stories_story_tags_story_id_23f247f5_fk_stories_story_id; Type: FK CONSTRAINT; Schema: public; Owner: food_user
--

ALTER TABLE ONLY public.stories_story_tags
    ADD CONSTRAINT stories_story_tags_story_id_23f247f5_fk_stories_story_id FOREIGN KEY (story_id) REFERENCES public.stories_story(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: stories_story_tags stories_story_tags_tag_id_191e51a8_fk_stories_tag_id; Type: FK CONSTRAINT; Schema: public; Owner: food_user
--

ALTER TABLE ONLY public.stories_story_tags
    ADD CONSTRAINT stories_story_tags_tag_id_191e51a8_fk_stories_tag_id FOREIGN KEY (tag_id) REFERENCES public.stories_tag(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: stories_storyimage stories_storyimage_story_id_ca40867d_fk_stories_story_id; Type: FK CONSTRAINT; Schema: public; Owner: food_user
--

ALTER TABLE ONLY public.stories_storyimage
    ADD CONSTRAINT stories_storyimage_story_id_ca40867d_fk_stories_story_id FOREIGN KEY (story_id) REFERENCES public.stories_story(id) DEFERRABLE INITIALLY DEFERRED;


--
-- PostgreSQL database dump complete
--

