# Generated by Django 4.1.7 on 2023-04-14 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0002_story_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='read_count',
            field=models.IntegerField(default=0),
        ),
    ]
